# Generated by Django 6.0.3 on 2026-04-09 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["departure_time"],
                name="airport_fli_departu_abe547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"],
                name="airport_ord_created_ff47a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"],
                name="airport_rou_source__5c8f4c_idx"
            ),
        ),
    ]
