# Generated by Django 6.0.3 on 2026-04-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_flight_airport_fli_departu_abe547_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"verbose_name_plural": "airplanes"},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name_plural": "routes"},
        ),
    ]
