# Generated by Django 6.0.4 on 2026-04-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_airplane_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["id"], "verbose_name_plural": "airplanes"},
        ),
    ]
